---
name: "Quality Checks"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  check-code-quality:
    name: "Check Code Quality"
    runs-on: ubuntu-latest
    steps:
      - run: echo "🚀 Job automatically triggered by ${{ github.event_name }}"
      - run: echo "🐧 Job running on ${{ runner.os }} server"
      - run: echo "🐙 Using ${{ github.ref }} branch from ${{ github.repository }} repository"

      - name: "Checkout code"
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - run: echo "🐙 ${{ github.repository }} repository was cloned to the runner."

      - name: "Prepare Java runtime"
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "21"

      - name: "Cache Clojure Dependencies"
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
          key: clojure-deps-${{ hashFiles('**/deps.edn') }}
          restore-keys: clojure-deps-

      - name: "Install tools"
        uses: DeLaGuardo/setup-clojure@13.4
        with:
          cli: 1.12.2.1565 # Clojure CLI
          cljstyle: 0.17.642
          clj-kondo: 2025.07.28

      - name: "Kaocha test runner"
        run: clojure -X:test/env:test/run

      - name: "Lint Clojure"
        run: clj-kondo --lint deps.edn --config '{:output {:pattern "::{{level}} file={{filename}},line={{row}},col={{col}}::{{message}}"}}'

      - name: "Check Clojure Style"
        run: cljstyle check --report

      - run: echo "🎨 style and format of Clojure code checked"

      - run: echo "🍏 Job status is ${{ job.status }}."
